### ISSUE TITLE
Outdoor temperature adjusted heating - details?

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#17]
Not an issue but more of a question.

This is not directly related to Shelly script but to `/JustNowRankDynamic` endpoint.

Could it be possible to have a little bit more information how the ranking hours are decided in the backend? I mean if it's possible to do that in a few sentences.

What's the time frame for ranking system? Is it something like minimum temperature for the whole day or for the next 48 hours or something like that?

Anyway I'm going to test it soon. Thanks again for these superb scripts!

**Comment by Spot-hinta-fi** [comment]
Yes, this API is not the easiest to undertand.  But temperature forecast is next 24 hours average. And that can be naturally change every hour at least a bit.   When these Shelly scripts call the API hourly, it makes the rank calculation "dynamic"

You can play with the API parameters, if you use Swagger to give the parameters, and then get the URL it generated. For example this:

https://api.spot-hinta.fi/JustNowRankDynamic?region=FI&rankAtZeroDegrees=5&rankAdjusterPercentage=10&minimumRank=5&priceAlwaysAllowed=3&postalCode=99800&debugMode=true

I usually test with some postal code in Lapland, to have minus temperatures... well at least during winter. And then you can modify for example that rankAdjusterPercentage to see how it affects the "Rank" calculation. With this parameter "debugMode" it prints out some info in response that how calculation happend and based on what values.

**Comment by artoaaltonen** [comment]
Awesome, thank you! Super helpful. Nice insights with `debugMode`. 👍
