### ISSUE TITLE
Feature request: optimize last hours of day

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#18]
Last hours of today (2023-02-10) are cheaper than any hours of tomorrow (2023-02-11).

Would be cool if we could take advantage of this and, for example, start heating a little bit earlier during the cheaper hours.

Something like `optimizeLastHours=2` would allow today's 22.00-23.59 to be used for next day's ranking.

I'm not sure if this is even possible as we would probably need to take yesterday's ranking also in to account.

Anyway, just wanted to drop the idea here if smarter minds can work this through and you feel this would be worth doing.

**Comment by frspp** [comment]
Good idea!

**Comment by Spot-hinta-fi** [comment]
Related to this, but not exactly like this... there now new API which returns only night hours between 22:00 and 07:59.  And rank calculated for these hours: https://api.spot-hinta.fi/JustNowRankNight

And for Shelly script, there is 200/400 API where you just give the number of hours: 
https://api.spot-hinta.fi/JustNowRankNight?Rank=3

There is in branch (which has exploded a bit larger than branch name says) is new minimal script, which uses this API.  So with that script you can search f.ex. 3 cheapest hours between 22:00 - 07:59 and day change does not matter. Exactly meant for "night electricity" use case.  Direct link to file if you want to test.

https://github.com/Spot-hinta-fi/Shelly/blob/error-handling-improvements/Scripts/Shelly-Minimal_water_heating_night.js

**Comment by artoaaltonen** [comment]
That's very good addition! 🔥

It pretty much covers the use case of the original post.

How do you feel about creating "dynamic" (forecast controlled) version of this new endpoint?

**Comment by artoaaltonen** [comment]
Tried the new endpoint last night like so:
```
https://api.spot-hinta.fi/JustNowRankNight?Rank=4
```

Seems that my script didn't work as expected though. It didn't start at all during hours of 2023-02-23.

I will look into this tonight. Quite likely something is broken at my end.

**Comment by artoaaltonen** [comment]
As dynamic version of `/JustNowRankNight` doesn't exist (at least yet), I've been thinking about the original feature request.

New `/JustNowRankNight` endpoint gave me an idea of new parameter.

So I'm introducing an idea of `rankHourOffset=-2` parameter.

Nothing else would change, but with `rankHourOffset=-2` the daily ranks for the next 24 hours would be calculated from 22:00 instead of 00:00.

This would solve the original request, help with optimizing for "night electricity hours" and, as I see it, would also be compatible with existing APIs.

Would love to hear your thoughts on this. Keep up the good work!
