### ISSUE TITLE
`/JustNowRankDynamic` and `RankAdjusterPercentage` max value

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#19]
On Swagger documentation it states that `rankAdjusterPercentage` parameter must be value of `0-20`.

However, nothing is said about that in the Shelly script:
https://github.com/Spot-hinta-fi/Shelly/blob/main/Scripts/Shelly-Outdoor_temperature_adjusted_heating.js

So the question is: what are the accepted values?

IMO it would make sense that the value could also be higher than 20 (for example when `rankAtZeroDegrees` === `1`).

**Comment by Spot-hinta-fi** [comment]
Currently it is indeed 0-20.  I can take this to API "roadmap" to modify max. number larger and will then also update scripts.

**Comment by artoaaltonen** [comment]
Perfect! 🙏

**Comment by Spot-hinta-fi** [comment]
> Perfect! 🙏

Now this is in API. Allows max. value 50.  And comment in script is coming in next merge.
