### ISSUE TITLE
Changes in `/CheapestPeriodTodayCheck` endpoint?

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#21]
Has there been some changes in `/CheapestPeriodTodayCheck` endpoint?

I'm calling the API like this:
```
https://api.spot-hinta.fi/CheapestPeriodTodayCheck/2?priorityHours=0,1,2,3,4,5,6
```

For some reason this failed to start my boiler today. I was expecting it to start at 02:00.

Am I missing something here?

![FpfVIrGWAAITTE1](https://user-images.githubusercontent.com/49676133/220729348-84633bea-47f8-4ad9-8e27-e291b50866a1.png)

**Comment by artoaaltonen** [comment]
Seems that it's ignoring `priorityHours` since boiler just started at 22.00.

**Comment by Spot-hinta-fi** [comment]
It is not very obvious how to use this APi. But priorityHour parameter alone just affects the rank. Not the price. So this API does not care about it as it is about the price.

But in combination of priceModifier, you can manipulate priorityHours price. If you use value like -100 you will give those hours huge price advantage and then cheapestPeriod search will fing cheapest period among those hours for sure.

**Comment by artoaaltonen** [comment]
I see! Thanks for clarification and `priceModifier` trick. 👍
