### ISSUE TITLE
Bug report: `/JustNowRankNight` 

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#22]
Sorry to bother again.

I was testing `/JustNowRankNight` endpoint at some point at `2023-02-23 22.00-23.59` and everything seemed to be working fine (`/JustNowRankNight?Rank=9` returned `200`).

However, during next day, at 3AM I'm only getting error `400`. Even without `Rank` parameter. Is there something I'm missing here (again)?

Few sample requests and responses:

```
Request URL: https://api.spot-hinta.fi/JustNowRankNight
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 20.107.224.17:443
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 3
Content-Type: application/json; charset=utf-8
Date: Fri, 24 Feb 2023 00:59:33 GMT
Request-Context: appId=cid-v1:bcaa7eb9-5ac3-497d-9ac5-397bee643201
```

```
Request URL: https://api.spot-hinta.fi/JustNowRankNight?rank=4
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 20.107.224.17:443
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 3
Content-Type: application/json; charset=utf-8
Date: Fri, 24 Feb 2023 01:03:33 GMT
Request-Context: appId=cid-v1:bcaa7eb9-5ac3-497d-9ac5-397bee643201
```

```
Request URL: https://api.spot-hinta.fi/JustNowRankNight?rank=5
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 20.107.224.17:443
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 3
Content-Type: application/json; charset=utf-8
Date: Fri, 24 Feb 2023 00:59:09 GMT
Request-Context: appId=cid-v1:bcaa7eb9-5ac3-497d-9ac5-397bee643201
```

```
Request URL: https://api.spot-hinta.fi/JustNowRankNight?rank=4
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 20.107.224.17:443
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 3
Content-Type: application/json; charset=utf-8
Date: Fri, 24 Feb 2023 00:56:19 GMT
Request-Context: appId=cid-v1:bcaa7eb9-5ac3-497d-9ac5-397bee643201
```

```
Request URL: https://api.spot-hinta.fi/JustNowRankNight?Rank=9
Request Method: GET
Status Code: 400 Bad Request
Remote Address: 20.107.224.17:443
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 3
Content-Type: application/json; charset=utf-8
Date: Fri, 24 Feb 2023 01:25:23 GMT
Request-Context: appId=cid-v1:bcaa7eb9-5ac3-497d-9ac5-397bee643201
```

**Comment by Spot-hinta-fi** [comment]
Without the parameter, it returns the list of hours that belong to the night period.  With parameter only it returns you status codes that are relevant.

But it wonders me why this last sample returned 400. Needs investigation.

**Comment by artoaaltonen** [comment]
> Without the parameter, it returns the list of hours that belong to the night period.

But it didn't. Entire content body was `400`. Hope this helps.

**Comment by artoaaltonen** [comment]
> > Without the parameter, it returns the list of hours that belong to the night period.
> 
> But it didn't. Entire content body was `400`. Hope this helps.

Just to clarify: this worked before midnight and it indeed returned a list.

At 3AM it didn't work.

So maybe this is somehow related to date change..?

**Comment by Spot-hinta-fi** [comment]
I will try to simulate it with code... or wait until date changes.... but fix is coming if there is some issue. :-)

**Comment by artoaaltonen** [comment]
Awesome! ✊

**Comment by artoaaltonen** [comment]
Confirmed: it's happening right after date change.

**Comment by Spot-hinta-fi** [comment]
> Confirmed: it's happening right after date change.
> 
> https://api.spot-hinta.fi/JustNowRankNight

Thanks a lot on testing this and finding the bug.  It should be now fixed and deployed. I will test myself today that fix works.

**Comment by artoaaltonen** [comment]
> Thanks a lot on testing this and finding the bug.

Happy to help! :) Thanks for fixing it. These APIs and scripts are super handy!

Btw if you ever need contributors to backend I would be very interested.

**Comment by Spot-hinta-fi** [comment]
This seemed to work now. Closing the issue.
