### ISSUE TITLE
Is the service api.spot-hints.fi working as expected?

### ISSUE THREAD

**Issue by ANGR77** [Spot-hinta-fi/Shelly#24]
HI! 

I saw on when running the monitoring diagnostics on my Shelly 1 PRo and the fine heating hotspot script that it looks like the api call is not responding right: 

shelly_http.cpp:184 0x3ffe2320 HTTPS GET https://api.spot-hinta.fi/JustNowRank/4/5?boosterHours=04,17&priorityHours=23,00,01,02,03,04,05,06&priorityHoursRank=4&region=SE3 (SSL CA *)
09:09:12
shelly_http.cpp:71 0x3ffe2320 HTTP got 400 Bad Request and 3 byte response

**Comment by Spot-hinta-fi** [comment]
Hi, yes... Status code 400 "Bad request" means that response is "false"... So price now is not within limits. When response is 200 "OK" then price is ok.
