### ISSUE TITLE
​/JustNowRankDynamic and minimumRank

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#25]
If `minimumRank` is set to **24** should the endpoint always return with `200 OK`?

If not, could you give some hints why not... 😅

Having some hard time understanding how 'minimumRank` should work.

Here's the URL I'm playing with:
https://api.spot-hinta.fi/JustNowRankDynamic?rankAtZeroDegrees=4&rankAdjusterPercentage=10&minimumRank=24&priceAlwaysAllowed=0&postalCode=20100&priorityHours=0%2C1%2C2%2C3%2C4%2C5%2C6&priceModifier=-100&debugMode=true

Thanks again for these scripts! 💯

**Comment by Spot-hinta-fi** [comment]
Hi, "minimumRank" is the lowest calculated Rank when temperature raises and heating need is lowering.  So this minimumRank parameter is not related to 200/400 response directly, but it just tells what is the minimum number of hours when temperature goes over zero.

Technically it has been configured so, that it cannot be larger than "rankAtZeroDegrees" parameter.  For example if you set it to Zero and now when it is warmer than 0C, you will see the result in Rank calculation:

https://api.spot-hinta.fi/JustNowRankDynamic?rankAtZeroDegrees=4&rankAdjusterPercentage=10&minimumRank=0&priceAlwaysAllowed=0&postalCode=20100&priorityHours=0%2C1%2C2%2C3%2C4%2C5%2C6&priceModifier=-100&debugMode=true

**Comment by artoaaltonen** [comment]
Thanks for such a fast reply!

I think this explains a lot:

> Technically it has been configured so, that it cannot be larger than "rankAtZeroDegrees" parameter.

Would you be willing to reconsider that limit/configuration?

My use case: set `minimumRank` temporarily to higher number. This would be the easiest solution to "force" heating after some time away from home (no need to disable any scripts etc).

I don't really see the reasoning for the current limit, but I'm sure there's something. :)

**Comment by Spot-hinta-fi** [comment]
Reasoning is that it is "ruining" all calculations if it is larger than rank at zero degrees.   But what you explained, you can achieve by changing the rankAtZeroDegrees temporarily higher. Then it heats more hours in all temperatures.

**Comment by artoaaltonen** [comment]
That's a pretty good reason. :D

Thanks for the tip. I'll look into that.

**Comment by artoaaltonen** [comment]
Could you maybe update the Swagger documentation to include the min/max values of minimumRank for the next person wondering this thing?

**Comment by Spot-hinta-fi** [comment]
I will have a look on this. Thanks for tip and feedback.
