### ISSUE TITLE
JustNowRankDynamic and negative PriceAlwaysAllowed

### ISSUE THREAD

**Issue by artoaaltonen** [Spot-hinta-fi/Shelly#26]
Are negative values allowed for PriceAlwaysAllowed?

I tried to use negative value but seems that relay still got turned on when price hit zero.

This is a bit problematic for us with a bad electricity deal... 😅

**Comment by Spot-hinta-fi** [comment]
It is now possible to make PriceAlwaysAllowed negative. So if you want to disable it, use f.ex "-99" value.
