### ISSUE TITLE
On/off 

### ISSUE THREAD

**Issue by Skankyhank** [Spot-hinta-fi/Shelly#28]
Hi.

Is it possible to invert the I/O status(?) for ”Shelly-Minimal_water_heating.js”? So when price is high, shelly turns on.

With current script it’s the other way around: Low price = shelly on.

Thanks

**Comment by Spot-hinta-fi** [comment]
You should do small mofification to the code. Basically just find the rows where relay is turned on or OFF and switch the controls opposite.  

I mean lines that contain this:  "Shelly.call("Switch.Set", "{ id:0, on:true}"

Just change **on:true** to **on:false**   and then **on:false** to **on:true**
