### ISSUE TITLE
Could not load price information.

### ISSUE THREAD

**Issue by Skankyhank** [Spot-hinta-fi/Shelly#34]
Hi!

Why do my script sometimes go to Backup, even though it should’t?

Testing request string (https://api.spot-hinta.fi/JustNowRank/6/2?boosterHours=99&priorityHours=02,03,04,21&priorityHoursRank=2&region=SE3) in web browser, the respons is: Could not load price information.

Btw, thank you for all your effort.

Regards Henrik

**Comment by Spot-hinta-fi** [comment]
Hi, there was Entso-E issue today.  Pricing data was not available until now it seems to be again working.... so widespead data distribution problem.

I will see if some backup source can be found for Sweden which is not dependand on Entso-E.

**Comment by Spot-hinta-fi** [comment]
And now there is a undisclosed :-) backup source which should resistant to Entso-E hickups.
