### ISSUE TITLE
Monitoring - Does the internet monitor work?

### ISSUE THREAD

**Issue by frspp** [Spot-hinta-fi/Shelly#37]
Hi! I think my Shelly 1PM Mini Plus has a working internet connection as it shows time right. The monitoring script says internet connection is not working - can it be trusted? 

FYI: I have another 1PM Mini Plus running Minimal Heating script and also a script that HTTP POST's the data to cloud server. It has had a robust internet during past few days and latest data was stored to the cloud 1 minute ago.

**Comment by Spot-hinta-fi** [comment]
Hi, this is a good question and frankly said I dont know how good internet monitoring is now.  It uses two indications: wifi is connected and then that shelly is connected with shelly cloud.

Now when I have seen how often Shelly cloud is not working, I have started to investigate better options to monitor the connection.

So dont trust it too much.  I will take it on agenda to review and refactor it.

**Comment by Spot-hinta-fi** [comment]
This is a good reason to refactor the script.  I dont like Shelly cloud dependency it has.

**Comment by Spot-hinta-fi** [comment]
Monitoring script has now been renewed and there is no dependency with Shelly cloud anymore.
