### ISSUE TITLE
Säätöviiveen kompensoiminen

### ISSUE THREAD

**Issue by anhil123** [Spot-hinta-fi/Shelly#38]
Olen testaillut tuota skriptiä "Shelly-Rank-and-Price.js" muutaman poäivän ajan ja pörssisähkäsopimus astuu voimaa vajaan viikonn päästä.

Kun Shelly muuttaa releen statusta, menee siinä ainakin oman lämpöpumpun (IVT) tapauksessa parikin minuuttia, ennen kuin pumppu sammuttaa itsensä, jos sillä on aktiivinen hetki päällänsä. Tällöin pumppu saattaa syödä tuon pari minuuttia kallista sähköä. Voisiko siis skriptiin asjatella lisättävän jonkun uuden parametrin tyyliin "MachineDelay_min" jonka asettavamlla vaikka itseni tapuksessa arvoon "2" Shelly osaisi aikaistaa noita avaa-sulje ja sulje-avaa toimenpiteitä tuon viiveen verran? Ei menisi senttiäkään ylimääräistä sähköyhtiölle... ;)

Muuten kyllä näyttä oikein hyvältä ja eiköhän täsdtä kahvirahat lähde matkaan...

**Comment by Spot-hinta-fi** [comment]
Hei, hienoa että skriptit toimivat.   

Tuosta viiveestä....  pumppu tosiaan tekee sen varmaan hoitaakseen ohjaukset hallitusti. Tuo muutos olisi skriptiin yllättävän suuri oikeastaan, kun pitäisi myös muuttaa taustajärjestelmää antamaan kysyttäessä tulevan tunnin ohjaus, eikä sen tunnin ohjausta jolloin kysely tarkalleen ottaen tehdään.

En uskalla siis luvata tätä toimintoa ja uskoisin, että kyse on kuitenkin aika pienestä tappiosta, vaikka kyllä omaakin pientä insinööri-mieltäni asia varmaan kaivelisi :-)

**Comment by anhil123** [comment]
Hei,

Kiitos nopeasta vastauksesta!

Kysymys on tosiaan periaatteellinen, eikä suurista summista puhuta. Insinööri se on tässäkin päässä ja siksi asian nostin pöydälle. Ymmärrettävää, että jos asian implementointi vaatisi suurta remonttia koodii, niin ei oikein maksa vaivaa 😉

T: Ari

⁣Get BlueMail for Android ​

**Comment by anhil123** [comment]
Moi,

Tässä ennätyskallin pörssisähköpäivän lähestyessä loppuaan huomasin kantapään kautta asia, joka lienee tarkoitettu näin olemaan eli "BoosterHours" ajaa yli arvon "MaxPrice". Itse en tätä ollut näin ajatellut ja sksi maksan siitä ihan käytännössä Helsingin Energialle ;)

Voisiko siis muutoksena skriptiin ajatella, että edes "BoosterHours" tunteina ei Shellyn relettä aktivoida, mikäli nuo ko. tunnit ovat kalliimpia kuin "MaxPrice"?
 
Tämä lienee jo pureksittu aihe, mutta kumminkin...
 
T: Ari Lahtinen
