### ISSUE TITLE
Yösähkö tunnit

### ISSUE THREAD

**Issue by jlehmusk** [Spot-hinta-fi/Shelly#54]
Yösähkön tunnit taitaa olla oletusarvoisesti väärin. "PriceModifier_Hours: [22, 23, 0, 1, 2, 3, 4, 5, 6, 7]" pitäisi olla "PriceModifier_Hours: [22, 23, 0, 1, 2, 3, 4, 5, 6]".

**Comment by Spot-hinta-fi** [comment]
Kiitoksia. Korjastin sen tuohon SmartHeating skriptiin.
