### ISSUE TITLE
Minimal heating not working?

### ISSUE THREAD

**Issue by frspp** [Spot-hinta-fi/Shelly#69]
Hi!
 
I upgraded to Shelly Plus 1PM to fw 1.2.2 and then copied latest Minimal-heating from Github. In past 1,5 days (8.4. 00-) it has turned relay on only for one hour; not all today even if now 15:00 is cheapest 3 hours (should turn on for cheapest 5 hours):
![Screenshot 2024-04-09 at 15 11 02](https://github.com/Spot-hinta-fi/Shelly/assets/22942340/8b59cc4d-ea32-4b9e-9f89-5c3f950b8496)

Shelly has correct time:
![Screenshot 2024-04-09 at 15 16 48](https://github.com/Spot-hinta-fi/Shelly/assets/22942340/53063011-1c31-4621-87d8-09d1010e17e0)

It worked fine with older FW with older code, before I updated.

Shelly Plus 1PM, fw 1.2.2 (latest stable available)

Settings:
```
// Thank you for your support: https://www.buymeacoffee.com/spothintafi
// Supported Shelly firmwares: 1.0.3 - 1.2.3. Script version: 2024-03-03

// Change these settings as you like
let Region = "FI"; // Supported regions: DK1, DK2, EE, FI, LT, LV, NO1, NO2, NO3, NO4, NO5, SE1, SE2, SE3, SE4
let Relays = [0]; // Relays to control. For example: [0,1,2]
let CheapestHours = "5";  // How many cheapest hours relay will be turned on? To ONLY use a price limit, put CheapestHours to "0".
let OnlyNightHours = false; // If true, cheapest hours are only searched from the night hours (22:00 - 07:00), false == all hours
let PriceAlwaysAllowed = "0"; // Below what hour price the relay can be always on (or off, if inverted)? Value is in full euro cents. Use "-999" to disable.
let BackupHours = [3, 4, 5, 6]; // If Internet connection is down, turn relay ON during these hours (0...23). Use [99], if you don't want any backup hours.
let Inverted = false; // If "true", relay logic is inverted (= relay is turned ON when price is too exepensive and OFF when cheap)

```

LOG:
```
SmartMonitoring: Monitored script 1 is running. All good. 15:09:32
SmartMonitoring: Monitored script 8 is running. All good. 15:09:32
Minimal-Heating: This hour has already been executed. Waiting for an hour change. 15:09:51
SmartMonitoring: Testing Internet connection... 15:10:01
SmartMonitoring: Internet connection is OK 15:10:04
```

**Comment by ml-bw** [comment]
Hi, have you also copied the SmartMonitoring script from GitHub? Because "PrivateKey" is generated only when getting from the library.  

But if you now stop the Minimal script and start again, what it prints then to LOG?

**Comment by Spot-hinta-fi** [comment]
Hmm.... strange thing. But I've seen once or twice that after upgrade script engine is somehow "stuck".  I do usually firmware upgrade so that I stop scripts, update firmware, reboot Shelly manually and then start scripts again.
