### ISSUE TITLE
VAT or other tax variable

### ISSUE THREAD

**Issue by Herberth404** [Spot-hinta-fi/Shelly#71]
Please ad to code own variable for VAT or other cost/tax. So in line the explanation tells that this given value is now for example 24% and included in electric price. If user wants to operate with some other value, like in autumn 25.5,  he can then just change this line. Taxes are changing and from this code it is not fully clear if there are any tax included and  what it is. Taxes vary from region to region so better transparency would be cleared for user.

like 
let Tax = [24.0]; // VAT or other tax current rate in percentage, included in output. For example: [24.0]. If [0] ,no tax will included in calculations

**Comment by Spot-hinta-fi** [comment]
Finnish tax change will be changed to the API by 1st of September.  Taxes are unfortunately more complex in Nordic countries than just one percentage.  Finland is easy part, but f.ex. Danish taxes rquire quite much coding (when properly done).

But good comment and idea.
