### ISSUE TITLE
Update procedure clarification

### ISSUE THREAD

**Issue by jurasjo** [Spot-hinta-fi/Shelly#9]
Hi, 
at first thank you for your hard work.

I would like to ask about the proper way of updating your scripts on a Shelly device. I use provided URL (http://api.spot-hinta.fi/Shelly/library) to download/install scripts on the Shelly. 

So when there is a new version of the script, should I delete the existing script and then use "Insert code" to install the newest version and then I would need to manually set parameters again?

**Comment by Spot-hinta-fi** [comment]
Hi, thanks.

Yes, you basically need to replace the script with new one and then setup parameters again. This is unfortunately so as Shelly scripts don't allows smooth upgrade process.  

I'm usually doing it so, that I copy-paste old script to text editor, then remove the script, install new and then fix parameters. It would not take more than minute and you can also copy old script back if you have any issue with new script.
